---
################################ 疎通確認 ######################################################################################
- name: ping
  ping:
################################ ssh設定 ######################################################################################
- name: mkdir .ssh
  file: dest=/home/{{ username }}/.ssh state=directory owner={{ username }} group={{ username }} mode=700
- name: add ssh keys
  template: owner={{ username }} group={{ username }} src={{ item }}.j2 dest=/home/{{ username }}/.ssh/{{ item }} mode=600
  with_items:
    - config
    - id_rsa
    - id_rsa.pub
    - ryugoo-infra-id-rsa
    - ryugoo-infra-id-rsa.pub
    - ryugoo-saba-id-rsa
    - ryugoo-saba-id-rsa.pub
################################ パッケージのインストール ########################################################################
- name: Add an Apt signing key, uses docker-ce key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add the Ansible repository
  apt_repository:
    repo: "ppa:ansible/ansible"
- name: Add the Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable test edge"
    state: present
    mode: 0644
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
# apt-cache policy <package> でインストール可能なバージョンを調べる
- apt: name={{item.name}} state=present
  with_items:
    - name: "ansible=2.5.*"
    - name: "python3-pip=8.*"
    - name: "python-pip=8.*"
    - name: "ruby=1:2.3.*"
    - name: "openjdk-8-jre-headless=*"
    - name: "nginx=1.*"
    - name: "docker-ce=18.*"
    - name: "jq=1.5+*"
    - name: git
- name: Add the Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
- name: user join to docker group
  user:
    name: ryugoo
    groups: docker
    append: yes
################################ gitリポジトリの配置 ############################################################################
- name: git clone RyuGoo-Infra
  become_user: ryugoo
  git:
    repo: git@github-ryugoo-infra:Rhelixa-inc/RyuGoo-Infra.git
    dest: "/home/{{ username }}/RyuGoo-Infra"
    version: master
  tags: git
- name: git clone RyuGoo-Infra
  become_user: ryugoo
  git:
    repo: git@github-ryugoo-saba:Rhelixa-inc/RyuGoo-Saba.git
    dest: "/home/{{ username }}/RyuGoo-Saba"
    version: master
  tags: git
